### PR TITLE
Support decimal number type keys in maps

### PR DESCRIPTION
**Pull request by aksentyev**
It is strange that bson package cannot resolve such cases, e.g. `encoding/json` package uses `encoding.TextMarshaler/encoding.TextUnmarshaler` interfaces for this, in spite of json does not support non string keys. I've done some changes to be able to use maps with decimal number type keys in models with this adapter.

### CODE REVIEW

**Comment by domodwyer** [comment]
Hi @aksentyev 

I was under the impression that integer keys were not supported by BSON as they conflict with the internal representation of arrays in the [spec](http://bsonspec.org/spec.html). Does MongoDB support integer keys in maps?

Dom

**Comment by aksentyev** [comment]
Hi @domodwyer! 

No, MongoDB does not support non string keys because it stores document in bson format. But I believe that encoder/decoder packages should be able to work with all standard types (at least numeric types in map keys) and  should be able to represent types if it needed.

`encoding/json` serializes int keys to string and vice versa (https://play.golang.org/p/DtPJ6TwB9sA)

I know that also some composite types (like structs) can be used as map keys in some cases, but if struct had a slice field it is evidently impossible (https://play.golang.org/p/vg6Vxi90CDg) to use is a map key. Strings and numeric types in map keys really covers 99% of use cases.

**Comment by domodwyer** [comment]
Hi @aksentyev 

I think I'm convinced! Would you mind rebasing or pulling development into your branch to clean up the diff and we'll review, thanks!

Dom

**Comment by domodwyer** [comment]
Thanks for the great PR @aksentyev!

Dom

**Pull request merged**
