### PR TITLE
Cluster abended test 254

### PR DESCRIPTION
**Pull request by jameinel**
This adds an explicit test for the Abended behavior that was added in issue #255. I'm not entirely sure what Copyright to assign, and I feel a little bad about peeking under the covers, but it wasn't clear if there was another way to actually test the behavior.

### CODE REVIEW

**Comment by jameinel** [comment]
I was able to reproduce this manually using "tcpkill".
I essentially had live connections to mongo, and used "lsof -i 27017" to find what sockets were connected to mongo. I then ran "tcpkill -i lo 'port 54321'" (you can use the mongo port, but it causes all connections to die, rather than just targeting a single one.)

By killing a single connection, the client side flags the server as "abended" and triggers the bad behavior.

**Comment by domodwyer** [comment]
Hi @jameinel 

I'm going to sort out the development/master branch diff - it's getting confusing! I'll get back to you regarding this PR (the conflict might not be an issue).

Thanks!
Dom

**Comment by jameinel** [comment]
The conflict is just because I did the same change vs mgo.v2 and didn't
rebase it onto your branch. I can just do that.

Do you want me to target Develop?
John
=:->

**Comment by domodwyer** [comment]
Hi John,

Yes please, that would be great! I think there's something weird going on with this diff though - I've already added a fix for this: https://github.com/globalsign/mgo/blob/896bbb89d21253a28cd5a7f8b81fe091410cb94d/cluster.go#L664

I'll still happily take the test that goes with it though!

Dom

**Comment by jameinel** [comment]
Rebased. I had to replay your patch on the branch I had started on, and I added a comment to justify why it was ok to do.

**Comment by domodwyer** [comment]
Hey @jameinel 

There's a rouge import for the old mgo in `server_test.go` that's causing tests to fail - can you swap it for this repo and we'll get this merged?

Thanks!
Dom

**Comment by jameinel** [comment]
Sorry about that, should be fixed now.

**Comment by jameinel** [comment]
It looks like you changed 'development' so I rebased again rather than bring in all the other 'master' patches.

**Comment by domodwyer** [comment]
Thanks @jameinel!

It's very much appreciated,

Dom

**Pull request merged**
