### PR TITLE
Additional metrics tracking

### PR DESCRIPTION
**Pull request by jacksontj**
This adds metrics to track:
- server/socket open/close
- pinger creations

### CODE REVIEW

**Comment by domodwyer** [comment]
Hey @jacksontj 

Looks good! Thanks for taking the time to open a PR however would you mind targeting the development branch? I don't imagine there's any issue as the locking is largely out of the hot paths but we typically verify performance before a release makes it to the `master` branch. 

Thanks again for the PR, it's really appreciated!

Dom

**Comment by jacksontj** [comment]
@domodwyer target branch changed. I had to rebase a bit, but the commits cherry-pick in just fine :)

**Review by domodwyer — APPROVED** [review]

**Comment by domodwyer** [comment]
Looks great, thanks @jacksontj - really appreciate the PR

Dom

**Comment by jacksontj** [comment]
@domodwyer It seems that I am not authorized to merge this PR. I'm not sure if thats because I don't have write permissions, or because one of the CI jobs seems to be stuck (hasn't completed in the days since I pushed).

**Comment by eminano** [comment]
Hi @jacksontj,

You can't merge the PR because you don't have write permissions :) 

The current build is quite broken (GitHub payload is missing a merge commit). Could you try to push to trigger the build again?

Thanks and sorry for the inconvenience!
Esther

**Review by eminano — APPROVED** [review]

**Comment by jacksontj** [comment]
@eminano I fetched but there are no new commits to put in, should I close and re-open the PR instead? (I'm not sure how to re-trigger your build, I usually hit the travis UI and click the "restart build" for my projects).

**Comment by domodwyer** [comment]
Hi @jacksontj 

Normally we would re-run the build, but in this case travis didn't pick up the branch at all. It's probably best to reopen as you suggest, sorry!

Thanks again!

**Comment by jacksontj** [comment]
PR closed and re-opened :)

**Comment by jacksontj** [comment]
There we go, travis ran and passed :tada:

**Comment by eminano** [comment]
Thanks a lot for your contribution @jacksontj!

**Pull request merged**
