### PR TITLE
Add lazy check connection after session creation

### PR DESCRIPTION
**Pull request by mjgarton**

### CODE REVIEW

**Comment by eminano** [comment]
Hi @mjgarton ,

Thanks for your PR!

However it's not very clear which scenario you are trying to solve with this change. The ping is done in ```DialWithInfo``` to ensure we're returning a session that has been established and the timeout value controls how long we wait for that connection. Is it not possible in your case (from looking at your test) to achieve the same result by either using a higher timeout value or handling the connection errors with retries on the client side?

Thanks!
Esther

**Comment by eminano** [comment]
Hi @mjgarton ,

Thanks for your PR!

However it's not very clear which scenario you are trying to solve with this change. The ping is done in ```DialWithInfo``` to ensure we're returning a session that has been established and the timeout value controls how long we wait for that connection. Is it not possible in your case (from looking at your test) to achieve the same result by either using a higher timeout value or handling the connection errors with retries on the client side?

Thanks!
Esther

**Comment by espencer** [comment]
Hi @eminano,

The scenario that this PR tries to fulfil is to allow to setup / create a mongo session in a non-blocking manner, even if the connection cannot be established to a MongoDB server.

Imagine you're writing some microservice which involves different persistence strategies, being only one of them mongo. Your microservice starts / setup the connection at bootstrap time; but you don't want your service to block until the connection is setup successfully. Perhaps the MongoDB server is down or not reachable.

This PR allows to instantiate a mongo session without performing the first (and blocking) check, delegating in the automatic connection refresh to perform the connection in a background goroutine.

Unfortunately seems that the PR cannot be merged automatically, as it was proposed a couple of years ago, and I don't have the required spare time to fix it.

**Comment by eminano** [comment]
Hi @espencer ,

Thanks for taking the time to clarify your scenario. 

What you're describing can be easily handled on the client side by just checking the error and retrying the dial (within a different goroutine if you don't want to block your service). It's cleaner and more intuitive for the library to just return an error letting you know if the connection has been established and let the client handle what to do about it. This way the driver logic is kept simple and flexible. 

Given the above reasoning I'll now close this PR. 

Thanks again for your contribution!

Esther

**Comment by mjgarton** [comment]
Having to implement that logic in lots of places and seeing it implemented inconsistently was what led me to extract it into shared code, before asking myself why it doesn't live inside `mgo`.

Another way of looking at this is this:

Currently, if mongodb is available and my applicaition starts up fine but them mongodb goes away, my application doesn't work but it will recover once mongodb comes back without my having to do anything special. (or at least I believe that's the case from last time I tested it)

 Why should mgo reconnect automatically in that case when mongodb becomes available, but not do the same if it's unavailable during startup?  I think that's inconsistent behaviour.

**Comment by eminano** [comment]
Hi @mjgarton,

It is not inconsistent behaviour because they are two very different scenarios.

When you first start up your db you have the ability to tell if the connection can be established or not, and having an error if you can't connect allows you to handle whatever issue is preventing it. 

Once the connection has been established you should rely on mongo's ability to recover by itself (failover on a multiple server cluster would be a prime example for this), which is why the reconnection is done automatically. 

Regarding having to implement the logic in multiple places, it sounds more like a middleware on the client side that is reusable and handles reconnection at startup than driver logic.

I hope this clarifies the reasoning for closing the issue.

Esther

**Pull request closed without merging**
