### PR TITLE
Fixing tests for 4.0

### PR DESCRIPTION
**Pull request by peterdeka**
There are still two tests failing on 4.0 not related to the auth strings.

### CODE REVIEW

**Comment by peterdeka** [comment]
Auth tests are actually ok.
Regarding the two tests still failing i'm asking @eminano @domodwyer advice:
- `autoIndexId:false` as per docs: 
> Starting in MongoDB 4.0, you cannot set the option autoIndexId to false when creating collections in databases other than the local database.
So how should we proceed? Do we have a way to understand if it's against the local database or we directly return an error if `autoIndexId:false` and the version is 4.0 or above?
- `Unrecognized field 'snapshot' i actually don't get it

**Comment by eminano** [comment]
@peterdeka Thanks a lot for taking the time to fix this!

Regarding the tests that are failing you can just skip them based on a version check as it's done for others:
https://github.com/globalsign/mgo/blob/master/session_test.go#L354

```Unrecognized field "snapshot"``` is a valid error since it's a protocol mismatch (using a feature that doesn't exist in 4.0). It's best to not try and "catch" error responses from mongo and convert them into specific errors in mgo given how volatile they are (they can change with every version - as you have discovered).

Hope this helps, let us know if you have any other questions.
Esther

**Comment by peterdeka** [comment]
Thanks @eminano, i just pushed but Travis is failing with (probably) network or GOROOT errors, i think you should be able to relaunch the builds maybe..

**Comment by domodwyer** [comment]
Hi @peterdeka 

Thanks very much! It's truly appreciated - thanks for all the contributions :)

Dom

**Pull request merged**
